# alembic/script.py.mako

"""Consolidate schema changes for v2 lifecycle

Revision ID: 361c3e1dccaf
Revises: 73a0ae07b290
Create Date: 2025-10-06 13:08:22.681265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361c3e1dccaf'
down_revision: Union[str, None] = '73a0ae07b290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.create_unique_constraint(None, 'api_keys', ['prefix'])
    # Adicionamos um server_default para preencher os dados existentes
    op.add_column('jobs', sa.Column('media_type', sa.String(length=50), nullable=False, server_default='video')) # <-- LINHA CORRIGIDA
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'media_type')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=True)
    # ### end Alembic commands ###