# alembic/versions/b44a70f35493_add_narration_table.py

"""Add narration table

Revision ID: b44a70f35493
Revises: 0_initial_schema
Create Date: 2025-09-27 09:05:31.114755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b44a70f35493'
down_revision: Union[str, None] = '0_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narrations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELED', name='narration_status_enum'), nullable=False),
    sa.Column('voice', sa.String(length=255), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_ended_at', sa.DateTime(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('result_audio_path', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    with op.batch_alter_table('narrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narrations_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_narrations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('narrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narrations_status'))
        batch_op.drop_index(batch_op.f('ix_narrations_job_id'))

    op.drop_table('narrations')

    # No downgrade, removemos também o tipo ENUM do banco
    narration_status_enum = postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELED', name='narration_status_enum')
    narration_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###